# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LinesAroundPoints
                                 A QGIS plugin
 This Plugin creates lines around a point layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-13
        copyright            : (C) 2020 by Andres Herrera
        email                : t763rm3n@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LinesAroundPoints class from file LinesAroundPoints.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lines_around_point import LinesAroundPoints
    return LinesAroundPoints(iface)
